version: '3'

services:
  example-awssqs:
    image: example-awssqs:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROSELYTE_R2DBC_URL=r2dbc:pool:postgres://host.docker.internal:5432/example-sqs
      - PROSELYTE_R2DBC_USER=postgres
      - PROSELYTE_R2DBC_PASSWORD=postgres
      - PROSELYTE_DB_URL=jdbc:postgresql://host.docker.internal:5432/example-sqs
      - PROSELYTE_DB_USER=postgres
      - PROSELYTE_DB_PASSWORD=postgres
      - PROSELYTE_AWS_ACCESS_KEY=[PUT_YOUR_ACCESS_KEY]
      - PROSELYTE_AWS_SECRET_KEY=[PUT_YOUR_SECRET_KEY]
      - PROSELYTE_AWS_REGION=us-east-1
      - PROSELYTE_SQS_QUEUE_NAME=example-sqs.fifo
      - PROSELYTE_SQS_QUEUE_REGION=us-east-1
    deploy:
      mode: replicated
      replicas: 3